---
- name: Install CryptoPro CSP
  ansible.builtin.include_tasks: install.yml

- name: Configure CryptoPro CSP baseline settings
  ansible.builtin.include_tasks: configure.yml

- name: Verify CryptoPro CSP installation
  ansible.builtin.include_tasks: verify.yml
