---
galaxy_info:
  author: Astra Automation Team
  description: Install and baseline configure CryptoPro CSP from local TGZ archive.
  company: Astra Linux
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: GenericLinux
      versions:
        - all
dependencies: []
